spring:  
  application:
    name: darphewebapp
  datasource:
    url: jdbc:postgresql://localhost:5432/darphedb
#  url: >-
#    postgres://uibnnvsoealdkh:aa21217c86348ed9048eac35fd9127b7d8e6aa2f67935c252a6860f4f6658d17@ec2-54-156-121-142.compute-1.amazonaws.com:5432/dek0k73gosues6
#    username: darphehyppolitejean
#    password: root2019
#    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      dll-auto: update
      naming:
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


# ===============================
## = Thymeleaf configurations (ThymeleafAutoConfiguration)
# ===============================
#spring.thymeleaf.mode=HTML
#spring.thymeleaf.cache=false
#spring.thymeleaf.encoding=UTF-8

## Data Source
#spring.datasource.url=postgres://uibnnvsoealdkh:aa21217c86348ed9048eac35fd9127b7d8e6aa2f67935c252a6860f4f6658d17@ec2-54-156-121-142.compute-1.amazonaws.com:5432/dek0k73gosues6
#spring.datasource.url=jdbc:mysql://localhost:3306/darphedb?verifyServerCertificate=false&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root2019

# JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.hibernate.naming.physical-strategy= org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
